version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    image: denbon05/devops-for-programmers-project-lvl1
    command: bash -c 'sleep 3 && npm test'
    volumes:
      - ./app/.env.example:/app/.env
    env_file: app/.env
    depends_on:
      - db

  db:
    image: postgres:14.5-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
