version: "3"

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./app:/app
    command: bash -c 'sleep 3 && npm start'

  caddy:
    image: caddy:2.5.2-alpine
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile